"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Bot, Box, Gamepad2, Headphones, LayoutGrid, Search, UserRound } from "lucide-react";
import { useRouter } from "next/navigation";
import { useI18n } from "@/components/I18nProvider";
import type { TranslationKey } from "@/lib/i18n";
type NavigationItem={labelKey:TranslationKey;descriptionKey:TranslationKey;href:string;keywords:string[];icon:"store"|"software"|"games"|"ai"|"support"|"account"};
const items:NavigationItem[]=[
{labelKey:"common.store",descriptionKey:"nav.storeDesc",href:"/marketplace",keywords:["store","marketplace","products","do‘kon","mahsulot"],icon:"store"},
{labelKey:"common.software",descriptionKey:"nav.softwareDesc",href:"/products",keywords:["software","apps","applications","dastur","ilova"],icon:"software"},
{labelKey:"common.games",descriptionKey:"nav.gamesDesc",href:"/games",keywords:["games","gaming","o‘yin"],icon:"games"},
{labelKey:"common.ai",descriptionKey:"nav.aiDesc",href:"/ai",keywords:["ai","artificial intelligence","sun’iy intellekt"],icon:"ai"},
{labelKey:"common.support",descriptionKey:"nav.supportDesc",href:"/support",keywords:["support","help","yordam"],icon:"support"},
{labelKey:"common.account",descriptionKey:"nav.accountDesc",href:"/account",keywords:["account","profile","library","hisob"],icon:"account"},];
function ItemIcon({type}:{type:NavigationItem["icon"]}){if(type==="store")return <LayoutGrid size={17}/>;if(type==="software")return <Box size={17}/>;if(type==="games")return <Gamepad2 size={17}/>;if(type==="ai")return <Bot size={17}/>;if(type==="support")return <Headphones size={17}/>;return <UserRound size={17}/>}
export function CommandPalette(){const[open,setOpen]=useState(false);const[query,setQuery]=useState("");const router=useRouter();const{t}=useI18n();useEffect(()=>{function onKey(event:KeyboardEvent){if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setOpen(current=>!current)}if(event.key==="Escape")setOpen(false)}window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);const filtered=useMemo(()=>{const normalized=query.trim().toLowerCase();if(!normalized)return items;return items.filter(item=>[t(item.labelKey),t(item.descriptionKey),...item.keywords].join(" ").toLowerCase().includes(normalized))},[query,t]);function close(){setOpen(false);setQuery("")}function go(href:string){close();router.push(href)}return <><button className="searchButton" type="button" onClick={()=>setOpen(true)} aria-label={t("nav.openQuick")} aria-haspopup="dialog" aria-expanded={open}><Search size={16}/><span>{t("nav.navigate")}</span><kbd>⌘ K</kbd></button>{open&&<div className="commandBackdrop" onMouseDown={close}><div className="commandPanel" onMouseDown={event=>event.stopPropagation()} role="dialog" aria-modal="true" aria-label={t("nav.quick")}><div className="commandInput"><Search size={18}/><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder={t("nav.find")} aria-label={t("nav.filter")}/></div><div className="commandResults">{filtered.map(item=><button key={item.href} type="button" onClick={()=>go(item.href)}><span className="commandIcon"><ItemIcon type={item.icon}/></span><span><strong>{t(item.labelKey)}</strong><small>{t(item.descriptionKey)}</small></span><ArrowUpRight size={15}/></button>)}{filtered.length===0&&<div className="commandEmpty">{t("nav.noMatch")}</div>}</div></div></div>}</>}
