import { BrainCircuit, CheckCircle2, FileSearch, Headphones, Search, ShieldCheck, Sparkles } from "lucide-react";
import { ProjectPlanner } from "@/components/ProjectPlanner";
const modules=[
  {icon:Search,title:"AI Search",text:"Natural-language discovery across products, games, documentation and services."},
  {icon:Sparkles,title:"Product Finder",text:"Recommend the right SysOne product or solution using user intent and verified catalog data."},
  {icon:FileSearch,title:"Documentation AI",text:"Answer from product documentation and release notes instead of generic guesses."},
  {icon:Headphones,title:"Support Assistant",text:"Resolve common issues first and hand the conversation to a human with context when needed."},
  {icon:BrainCircuit,title:"Project Planner",text:"Turn an early idea into a structured product brief, modules and next actions."},
  {icon:ShieldCheck,title:"Permission-aware AI",text:"AI actions are constrained by roles, verified state and explicit user authorization."}
];
export default function AIPage(){return <div className="pageWrap"><section className="pageHero shell"><span className="eyebrow">SYSONE AI</span><h1>Intelligence where it actually helps.</h1><p>SysOne AI is designed as a product layer — grounded in trusted knowledge, transparent permissions and human handoff — rather than a decorative chatbot.</p></section><section className="section compactTop"><div className="shell"><div className="aiModuleGrid">{modules.map(({icon:Icon,title,text})=><article className="surface" key={title}><span className="iconChip"><Icon/></span><h2>{title}</h2><p>{text}</p><span className="futureBadge">Architecture ready</span></article>)}</div></div></section><section className="section sectionTint"><div className="shell"><ProjectPlanner/></div></section><section className="section"><div className="shell policyPanel surface"><div><span className="eyebrow">AI RELIABILITY MODEL</span><h2>Know what the assistant knows.</h2></div><div className="checkList vertical"><span><CheckCircle2/>Product prices come from the product database.</span><span><CheckCircle2/>Availability comes from real system state.</span><span><CheckCircle2/>AI cannot change payments or permissions by itself.</span><span><CheckCircle2/>Users can control personalization.</span><span><CheckCircle2/>Support can take over with conversation context.</span></div></div></section></div>}
